from __future__ import annotations

from typing import Any, Protocol


class Logger(Protocol):
    def debug(self, msg: str, **ctx: Any) -> None: ...
    def info(self, msg: str, **ctx: Any) -> None: ...
    def warning(self, msg: str, **ctx: Any) -> None: ...
    def error(self, msg: str, **ctx: Any) -> None: ...
