import { MigrationInterface, QueryRunner } from "typeorm";

// Generated by: npm run migration:generate -- migrations/InitialSchema
// Covers: users, audit_log, outbox (including DLQ columns attempts/last_error/dead_at).
//
// Re-running `migration:generate` against a schema that already matches these
// entities should produce an empty diff — that invariant verifies the
// migration is complete and up-to-date. (See auth README: "Verify migration".)
//
export class InitialSchema1749772800000 implements MigrationInterface {
  name = "InitialSchema1749772800000";

  async up(qr: QueryRunner): Promise<void> {
    // uuid_generate_v4() is what TypeORM 0.3.x emits in generated DDL for
    // @PrimaryGeneratedColumn("uuid") on PostgreSQL. Using the same function
    // keeps `migration:generate` idempotent: a re-run against a schema that
    // already has this migration applied produces an empty diff.
    await qr.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);

    // ------------------------------------------------------------------
    // users — the auth aggregate. `id` is app-generated (UserId.generate)
    // so it carries no default; the service sets it before the INSERT.
    // ------------------------------------------------------------------
    await qr.query(`
      CREATE TABLE "users" (
        "id"            uuid                     NOT NULL,
        "email"         character varying(320)   NOT NULL,
        "password_hash" character varying(255)   NOT NULL,
        "roles"         text[]                   NOT NULL DEFAULT '{user}',
        "created_at"    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updated_at"    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_users"       PRIMARY KEY ("id"),
        CONSTRAINT "UQ_users_email" UNIQUE ("email")
      )
    `);
    // TypeORM @Index() on email for user-by-email lookups.
    await qr.query(
      `CREATE INDEX "IDX_users_email" ON "users" ("email")`,
    );

    // ------------------------------------------------------------------
    // audit_log — append-only security trail written in the same
    // transaction as the business write.
    // ------------------------------------------------------------------
    await qr.query(`
      CREATE TABLE "audit_log" (
        "id"          uuid                     NOT NULL DEFAULT uuid_generate_v4(),
        "occurred_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "actor_id"    uuid,
        "action"      character varying(80)    NOT NULL,
        "target_id"   character varying(120),
        "details"     jsonb                    NOT NULL DEFAULT '{}',
        "ip"          inet,
        CONSTRAINT "PK_audit_log" PRIMARY KEY ("id")
      )
    `);
    await qr.query(
      `CREATE INDEX "IDX_audit_log_occurred_at" ON "audit_log" ("occurred_at")`,
    );
    await qr.query(
      `CREATE INDEX "IDX_audit_log_actor_id" ON "audit_log" ("actor_id")`,
    );
    await qr.query(
      `CREATE INDEX "IDX_audit_log_action" ON "audit_log" ("action")`,
    );

    // ------------------------------------------------------------------
    // outbox — transactional relay to Kafka.
    //
    // DLQ columns (attempts / last_error / dead_at):
    //   - `attempts`   INT NOT NULL DEFAULT 0  — bumped on every failed publish
    //   - `last_error` TEXT                    — last failure message
    //   - `dead_at`    TIMESTAMPTZ             — set when attempts >= OUTBOX_MAX_ATTEMPTS;
    //                                            poller skips rows where dead_at IS NOT NULL.
    //
    // Partial index on created_at WHERE published_at IS NULL drives the
    // poller's ORDER BY + LIMIT query; only unpublished rows are indexed.
    // ------------------------------------------------------------------
    await qr.query(`
      CREATE TABLE "outbox" (
        "id"           uuid                     NOT NULL DEFAULT uuid_generate_v4(),
        "aggregate_id" character varying(120)   NOT NULL,
        "topic"        character varying(120)   NOT NULL,
        "event_name"   character varying(120)   NOT NULL,
        "payload"      jsonb                    NOT NULL,
        "headers"      jsonb                    NOT NULL DEFAULT '{}',
        "created_at"   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "published_at" TIMESTAMP WITH TIME ZONE,
        "attempts"     integer                  NOT NULL DEFAULT 0,
        "last_error"   text,
        "dead_at"      TIMESTAMP WITH TIME ZONE,
        CONSTRAINT "PK_outbox" PRIMARY KEY ("id")
      )
    `);
    await qr.query(`
      CREATE INDEX "IDX_outbox_pending"
        ON "outbox" ("created_at")
       WHERE published_at IS NULL
    `);
  }

  async down(qr: QueryRunner): Promise<void> {
    await qr.query(`DROP INDEX IF EXISTS "IDX_outbox_pending"`);
    await qr.query(`DROP TABLE IF EXISTS "outbox"`);

    await qr.query(`DROP INDEX IF EXISTS "IDX_audit_log_action"`);
    await qr.query(`DROP INDEX IF EXISTS "IDX_audit_log_actor_id"`);
    await qr.query(`DROP INDEX IF EXISTS "IDX_audit_log_occurred_at"`);
    await qr.query(`DROP TABLE IF EXISTS "audit_log"`);

    await qr.query(`DROP INDEX IF EXISTS "IDX_users_email"`);
    await qr.query(`DROP TABLE IF EXISTS "users"`);
  }
}
