"""
MCP server for the memory service.

Exposes three tools:
  - memory_search   : hybrid graph+vector search over the user's episodes
  - add_episode     : persist a new memory episode
  - list_entities   : list entities extracted from the user's knowledge graph

Each tool receives `owner_id` explicitly so the server is stateless and
multi-tenant — the ai-agents service injects it from the session context
when constructing tool calls via langchain-mcp-adapters.
"""
from mcp.server.fastmcp import FastMCP

from ..application.memory_service import MemoryService


def make_mcp_server(service: MemoryService) -> FastMCP:
    mcp = FastMCP("memory-mcp")

    @mcp.tool()
    async def memory_search(
        query: str,
        owner_id: str,
        k: int = 10,
    ) -> list[dict]:
        """
        Search long-term episodic memory and knowledge graph.

        Returns a ranked list of memory hits, each with an excerpt of the
        remembered content, the entities Graphiti extracted, a relevance
        score, and the source type (conversation / document / web).
        """
        hits = await service.search(owner_id=owner_id, query=query, k=k)
        return [
            {
                "episode_id": h.episode_id,
                "excerpt": h.excerpt,
                "score": h.score,
                "source": h.source,
                "entities": h.entities,
            }
            for h in hits
        ]

    @mcp.tool()
    async def add_episode(
        content: str,
        owner_id: str,
        source: str = "conversation",
    ) -> str:
        """
        Persist a new memory episode for the user.

        `source` should be one of: "conversation", "document", "web".
        Returns the assigned episode id.
        """
        return await service.add_episode(
            owner_id=owner_id, content=content, source=source
        )

    @mcp.tool()
    async def list_entities(
        owner_id: str,
        limit: int = 50,
    ) -> list[dict]:
        """
        Return the top entities extracted from the user's knowledge graph.

        Each entity has a name, type (e.g. Person, Concept, Event), and
        an optional summary generated by Graphiti.
        """
        entities = await service.list_entities(owner_id=owner_id, limit=limit)
        return [
            {"name": e.name, "type": e.type, "summary": e.summary}
            for e in entities
        ]

    return mcp
